"""Export public clues and region geometry for the isolated Three.js preview."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
level=json.loads((ROOT/'web/data/levels/inner-sea-journey-v1.json').read_text(encoding='utf-8'))
data={'source':'inner-sea-journey-v1 (atlas revision 7, read-only snapshot)',
      'width':level['width'],'height':level['height'],'regionMap':level['regionMap'],
      'regions':[{key:r[key] for key in ('id','name','cells','clues')} for r in level['regions']]}
(ROOT/'web/prototypes/imperial-table/board-data.mjs').write_text(
    '// Generated by tools/sync_atlas_snapshot.py; no answers or storage.\nexport const boardData='
    +json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
