// UI and teaching copy only; country/banquet prose comes from the level.
export const journeyCopy = {
  en: {
    titleLead:"King Varo’s",titleTail:"Table",titlePrologue:"Seven countries are served at one table.\nFollow a dish to the shore where its story began.",titleColophon:"THE SEA REMEMBERS",newStart:"A new journey",remember:"Remember the past",endAll:"End it all",backTitle:"Return to title",exitHeading:"The feast is over.",exitBody:"The lamps are out. You may close this tab.",
    backMenu:"Back to menu", backList:"Back to notes", arrivalNote:"Food & origins", halfwayNote:"Local life", newNote:"New", exploreMotif:"Discover {motif}",
    title: "King Varo's Table", chapter: "THE INNER SEA", titleKicker: "SEVEN KINGDOMS · ONE LAST FEAST",
    opening: "Seven dishes await the guests, but their place names have faded from the map. Begin with Pel's warm crab soup: restore the island and find the story that belongs beside its plate.",
    markedProgress:"Marked {count} / {total}", readOnly:"Restored · read-only", completedHelp:"Complete. Read Country record, or return to the title to begin anew.",
    readCountry:"Country record", viewLandscape:"Restored coast", separateRun:"Separate playthrough", restart:"Start again · keep original progress", original:"Return to original progress", resumeRun:"Continue separate playthrough", restartHelp:"Starting again creates a separate save. Return to your original progress at any time from this menu.",
    independent:"YOUR TURN", conflictAt:"Check row {row}, column {column}: the outlined clue conflicts with the marks in its counted area. Recheck that area or undo your last move.",
    coastTitle:"Pel · The winter without sails", coastCaption:"The shore remains; the landing stands empty, with no boats at its moorings. The island outline follows your restored light and dark cells.",
    menu: "Menu", overview: "Whole map", focus: "Focus", bright: "Bright", dark: "Dark", erase: "Erase", move: "Move",
    undo: "Undo", redo: "Redo", hint: "Hint", clearErrors: "Clear errors", read: "Read", skip: "Skip guidance",
    loading: "Unfolding the map…", begin: "Begin", resume: "Continue", continue: "Continue",
    settingsPractice: "Settings & practice", close: "Close", return: "Return to map", newJourney: "Open the new map",
    practiceLegacy: "Practice & previous edition", archive: "Collected notes", help: "How to play", check: "Check this map",
    language: "Language", legacyExplanation: "Opening a practice replaces the current journey. Your progress saves automatically.",
    retry: "Try again", loadFailed: "The map could not be opened. Check your connection and try again.",
    localFile: "Open this game through npm start and http://localhost:4173, rather than a file:// address.",
    storageUnavailable: "Saving is unavailable in this browser. Keep this tab open; progress may not survive a refresh.",
    mapLabel: "Interactive logic map", zoomIn: "Zoom in", zoomOut: "Zoom out",
    tools: "Board tools", feedback: "Current note", progress: "{count} / {total}",
    unknown: "unknown", markedBright: "bright", markedDark: "dark", clue: "clue {value}", noClue: "no number",
    cell: "{country}, row {row}, column {column}, {clue}, {state}",
    hintCenter: ", hint clue, strong outline", hintScope: ", clue scope, soft outline",
    country: "{country}: {count} / {total} marked", complete: "Restored", waiting: "Explore after the opening, or skip guidance",
    guide: "FIRST STEPS", travel: "AT THE TABLE", instruction: "YOUR NEXT MOVE", banquetEnding: "THE BANQUET ENDS",
    guideZero: "This 0 counts its own cell too. Every cell in its outlined country area must be dark. Choose Dark, then mark them.",
    guideFull: "Every outlined cell must be bright, including the number. With a mouse, try holding and dragging across adjacent cells; one Undo removes the whole stroke. On touch, tap to mark.",
    guideBorder: "You have learned zeroes and full counts. Now finish the island yourself: count only within the thick border. Hint can point you to a number when you need it.",
    guideRepair: "A mark conflicts with these clues. Undo it, or use Clear errors; your correct marks stay.",
    hintText: "Row {row}, column {column}: {value}. Strong outline: the clue. Soft outline: its counted area.",
    noHint: "No direct step here. Try Check this map, clear wrong marks, or choose another unfinished country.",
    contradiction: "These marks conflict with a clue. Use Undo or Clear errors.",
    removed: "{count} wrong marks removed. Correct marks were kept.",
    checkGood: "No conflicting marks found. Unknown cells still need your decision.",
    checkBad: "Some marks conflict with the clues. Clear errors removes only wrong marks.",
    allDone: "The map is complete. Explore it again, or read the collected records.",
    chooseNext: "A record has been put away. Choose another country on the map.",
    zoomToEdit: "Choose a country, or zoom in to read and mark its cells.",
    chooseCountry: "Choose a country to begin. You can return to this view at any time.",
    lockedCountry: "Finish the opening island, or choose Skip guidance to explore freely.",
    fall: "A RECORD OF THE FALL", trace: "WHAT REMAINS", motif: "THE RESTORED IMAGE", epilogue: "AFTER THE FEAST",
    finishOpening: "Explore the inner sea", backMap: "Return to map", nextPractice: "Next practice leaf", endPractice: "This practice is complete. Continue your journey.",
    noteEmpty: "The first note awaits your arrival.", banquet: "The banquet", records: "Country records",
    helpBody: "Each number counts bright cells in its centered 3×3 area, including itself, but only within the same country. A 0 means all dark. If the remaining bright count equals the unknown count, all unknown cells are bright. Thick borders always clip the scope.\n\nUse Bright, Dark or Erase, then click or tap. Repeat a mark to erase it. Mouse/pen: drag to paint one stroke. Right-click or Shift+click marks dark. Move tool, Space+drag or middle mouse pans; the wheel zooms. Touch: drag to pan, pinch to zoom, tap to mark.\n\nKeyboard: 1/2/3/4 choose tools; arrows move between cells; Enter uses your tool; Delete erases. Ctrl/⌘ Z undoes; Ctrl Y or ⇧⌘ Z redoes. A whole stroke is one undo.\n\nHint uses your current marks: one strong clue outline, its counted area softly outlined. Clear errors affects the entire loaded map, retaining correct marks.",
  },
  "zh-CN": {
    titleLead:"瓦罗王的",titleTail:"餐桌",titlePrologue:"他们把七个国家，端上了同一张餐桌。\n循着一道菜的来处，听见山河未尽的故事。",titleColophon:"潮水记得一切",newStart:"新的旅程",remember:"回忆往昔",endAll:"结束这一切",backTitle:"返回标题",exitHeading:"宴席已散。",exitBody:"灯火已熄。现在可以关闭这个页面。",
    backMenu:"返回菜单", backList:"返回笔记列表", arrivalNote:"食物与来处", halfwayNote:"当地生活", newNote:"新笔记", exploreMotif:"探寻{motif}",
    title: "瓦罗王的餐桌", chapter: "内海", titleKicker: "七国山河 · 一席往事",
    opening: "七道菜等着宾客，地图上的产地却已模糊。先从佩尔岛的热蟹汤开始：复原小岛，找回这只盘子旁应该写下的故事。",
    markedProgress:"已标记 {count} / {total}", readOnly:"已复原 · 只读", completedHelp:"已完成，可平移缩放回看。故事见“国家记录”；开始新的旅程请返回标题。",
    readCountry:"国家记录", viewLandscape:"复原图景", separateRun:"独立试玩", restart:"从头试玩 · 保留原进度", original:"返回原进度", resumeRun:"继续独立试玩", restartHelp:"从头试玩会建立独立存档；随时可从此菜单返回原进度。",
    independent:"现在由你推理", conflictAt:"检查第{row}行第{column}列：框出的数字与范围内标记冲突。请重新检查这片范围，或撤销上一笔。",
    coastTitle:"佩尔岛 · 无帆之冬", coastCaption:"海岸仍在，木栈桥尽头的系船环却空着。小岛轮廓沿你复原的亮暗格描出，船帆已不见。",
    menu: "菜单", overview: "查看全图", focus: "聚焦", bright: "亮格", dark: "暗格", erase: "擦除", move: "移动",
    undo: "撤销", redo: "重做", hint: "提示", clearErrors: "清除错误", read: "阅读", skip: "跳过引导",
    loading: "正在展开地图……", begin: "开始", resume: "继续旅程", continue: "继续",
    settingsPractice: "设置与练习", close: "关闭", return: "返回地图", newJourney: "进入新版地图",
    practiceLegacy: "练习与旧版地图", archive: "已收录的笔记", help: "玩法与操作", check: "检查当前地图",
    language: "语言", legacyExplanation: "打开练习会替换当前旅程，进度会自动保存。",
    retry: "重试", loadFailed: "地图未能打开。请检查网络连接后重试。",
    localFile: "请运行 npm start 并通过 http://localhost:4173 打开游戏，不要直接打开 file:// 文件。",
    storageUnavailable: "当前浏览器无法保存。请保持本标签页打开，刷新可能丢失进度。",
    mapLabel: "可交互逻辑地图", zoomIn: "放大", zoomOut: "缩小",
    tools: "棋盘工具", feedback: "当前笔记", progress: "{count} / {total}",
    unknown: "未知", markedBright: "亮格", markedDark: "暗格", clue: "线索 {value}", noClue: "无数字",
    cell: "{country}，第{row}行第{column}列，{clue}，当前{state}",
    hintCenter: "，提示数字，强高亮", hintScope: "，计数范围，弱高亮",
    country: "{country}：已标记 {count} / {total}", complete: "已复原", waiting: "首国完成后探索，也可跳过引导",
    guide: "从这里开始", travel: "餐桌纪事", instruction: "下一步", banquetEnding: "晚宴终章",
    guideZero: "这个 0 也计算数字格自身。框内属于本国的格子一定全暗：选中暗格工具，再逐一标记。",
    guideFull: "框内连同数字格都应标亮。用鼠标时，试着按住拖过相邻格，一次撤销可还原整笔；触屏请逐格轻点。",
    guideBorder: "你已掌握零线索与满数。接下来自己复原小岛：只计算粗国界内的格子；需要时，提示会指出一个可以继续推理的数字。",
    guideRepair: "有标记与线索冲突。可以撤销，或清除错误；正确标记会保留。",
    hintText: "第{row}行第{column}列的 {value}：强框是数字，弱框是它实际计算的范围。",
    noHint: "这里暂时没有直接步骤。可检查地图、清除错误，或选择另一个未完成的国家。",
    contradiction: "当前标记与线索冲突。可以撤销，或清除错误。",
    removed: "已清除 {count} 个错误标记，正确标记保留。",
    checkGood: "未发现冲突标记，未知格仍需继续判断。",
    checkBad: "有标记与线索冲突。清除错误只会移除写错的部分。",
    allDone: "地图已经完整。可以自由回看，或阅读已收录的记录。",
    chooseNext: "记录已收好。请选择地图上的另一个国家。",
    zoomToEdit: "选择一个国家，或放大到能清楚阅读数字的尺度后填格。",
    chooseCountry: "选择一个国家开始；随时可以回到全图。",
    lockedCountry: "请先完成开场小岛，或选择“跳过引导”自由探索。",
    fall: "陷落记录", trace: "留存之物", motif: "复原的图案", epilogue: "散席以后",
    finishOpening: "展开内海", backMap: "返回地图", nextPractice: "下一张练习", endPractice: "这张练习已经完成，继续下一段旅程。",
    noteEmpty: "第一则笔记，等待你抵达。", banquet: "晚宴纪事", records: "各国记录",
    helpBody: "每个数字统计以自身为中心、包含数字格的 3×3 内有多少亮格，但只计算同一国家。0 表示全暗；剩余亮格数与未知格数相等时，未知格全亮。粗国界始终会裁剪计数范围。\n\n选择亮格、暗格或擦除，然后点击或轻触。重复当前标记会恢复未知。鼠标／笔按住可连续涂色；右键或 Shift+点击标暗。移动工具、空格+拖动、中键拖动用于平移；滚轮缩放。触屏拖动平移、双指缩放、单击标记。\n\n键盘：1/2/3/4 选择工具，方向键移动格子，Enter 使用工具，Delete 擦除；Ctrl/⌘ Z 撤销，Ctrl Y 或 ⇧⌘ Z 重做。整笔涂色只占一次撤销。\n\n提示只依据当前标记：数字强高亮，同国计数范围弱高亮。清除错误作用于整张已载入地图，只移除写错的标记。",
  },
};

export function createJourneyText(i18n) {
  return (key, params = {}) => (journeyCopy[i18n.locale]?.[key] ?? journeyCopy.en[key] ?? key)
    .replace(/\{(\w+)\}/g, (match, name) => Object.hasOwn(params,name) ? String(params[name]) : match);
}
